image: mcr.microsoft.com/playwright/java:v1.40.0-jammy
workflow:
  name: "Regression Test Suite Run - $CI_COMMIT_REF_NAME"

stages:
  - test

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  PLAYWRIGHT_HEADLESS: "true" # Гарантируем headless-режим

API & UI Automated Tests:
  stage: test
  script:
    - chmod +x ./gradlew
    # Включаем headless через системные параметры Java (если передаешь через System.getProperty)
    - ./gradlew clean test -Dheadless=true -Dapi.thinkingEmail="$THINKING_EMAIL" -Dapi.thinkingPassword="$THINKING_PASSWORD"

  artifacts:
    when: always
    paths:
      - build/reports/tests/test/
      - target/playwright/ # Если сохраняешь скриншоты/трассировки
    reports:
      junit: build/test-results/test/TEST-*.xml
    expire_in: 1 week